server:
  port: 8081

spring:
  config:
    import: "nacos:userservice-dev.yaml"
  application:
    name: user-service
  datasource:
    username: postgres
    password: zxyxxxxxxx
    url: jdbc:postgresql://localhost:5432/test
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
        group: dev
#        cluster-name: ZH #集群名
      config: #拉取nacos配置需要
        file-extension: yaml
        server-addr: "127.0.0.1:8848"
  ai:
    # api和key分享自：https://pgthinker.me/2023/10/03/196/
    openai:
      api-key: sk-W9kYeE3JfWM86sr66exxxxxxxxxx
      base-url: https://api.mnzdna.xyz
      chat:
        options:
          temperature: 0.7
#  autoconfigure:
#    exclude:
#      - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration



  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
