server:
  port: 8081

spring:
  config:
    import: "nacos:userservice-dev.yaml"
  application:
    name: user-service
  datasource:
    username: postgres
    password: zxyxxxxxxx
    url: jdbc:postgresql://localhost:5432/test
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
        group: dev
#        cluster-name: ZH #集群名
      config: #拉取nacos配置需要
        file-extension: yaml
        server-addr: "127.0.0.1:8848"
  ai:
    # api和key分享自：https://pgthinker.me/2023/10/03/196/
    openai:
      api-key: sk-W9kYeE3JfWM86sr66e29FfC7xxxxxxxxxxxx
      base-url: https://api.mnzdna.xyz
      chat:
        options:
          temperature: 0.7
#  autoconfigure:
#    exclude:
#      - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: chat
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    #设置JWT签名时使用的密钥
    user-secret-key: chat
    #设置JWT过期时间
    user-ttl: 7200000
    #设置前端传递过来的令牌名称
    user-token-name: authentication
